// Code generated by cqgen, DO NOT EDIT.
// +build !websocket

package cqp

/*
#include <stdint.h>
#define CQEVENT extern int32_t __stdcall

extern char * _appinfo();
extern int32_t _on_enable();
extern int32_t _on_disable();
extern int32_t _on_start();
extern int32_t _on_exit();
extern int32_t _on_private_msg(int32_t, int32_t, int64_t, char *, int32_t);
extern int32_t _on_group_msg(int32_t, int32_t, int64_t, int64_t, char *, char *, int32_t);
extern int32_t _on_discuss_msg(int32_t, int32_t, int64_t, int64_t, char *, int32_t);
extern int32_t _on_group_upload(int32_t, int32_t, int64_t, int64_t, char *);
extern int32_t _on_group_admin(int32_t, int32_t, int64_t, int64_t);
extern int32_t _on_group_member_decrease(int32_t, int32_t, int64_t, int64_t, int64_t);
extern int32_t _on_group_member_increase(int32_t, int32_t, int64_t, int64_t, int64_t);
extern int32_t _on_friend_add(int32_t, int32_t, int64_t);
extern int32_t _on_friend_request(int32_t, int32_t, int64_t, char *, char *);
extern int32_t _on_group_request(int32_t, int32_t, int64_t, int64_t, char *, char *);
extern char* __stdcall AppInfo(){ return _appinfo(); }CQEVENT EVENT_ON_ENABLE() { return _on_enable(); }
CQEVENT EVENT_ON_DISABLE() { return _on_disable(); }
CQEVENT EVENT_ON_START() { return _on_start(); }
CQEVENT EVENT_ON_EXIT() { return _on_exit(); }
CQEVENT EVENT_ON_PRIVATE_MSG(int32_t var0, int32_t var1, int64_t var2, char * var3, int32_t var4) { return _on_private_msg(var0, var1, var2, var3, var4); }
CQEVENT EVENT_ON_GROUP_MSG(int32_t var0, int32_t var1, int64_t var2, int64_t var3, char * var4, char * var5, int32_t var6) { return _on_group_msg(var0, var1, var2, var3, var4, var5, var6); }
CQEVENT EVENT_ON_DISCUSS_MSG(int32_t var0, int32_t var1, int64_t var2, int64_t var3, char * var4, int32_t var5) { return _on_discuss_msg(var0, var1, var2, var3, var4, var5); }
CQEVENT EVENT_ON_GROUP_UPLOAD(int32_t var0, int32_t var1, int64_t var2, int64_t var3, char * var4) { return _on_group_upload(var0, var1, var2, var3, var4); }
CQEVENT EVENT_ON_GROUP_ADMIN(int32_t var0, int32_t var1, int64_t var2, int64_t var3) { return _on_group_admin(var0, var1, var2, var3); }
CQEVENT EVENT_ON_GROUP_MEMBER_DECREASE(int32_t var0, int32_t var1, int64_t var2, int64_t var3, int64_t var4) { return _on_group_member_decrease(var0, var1, var2, var3, var4); }
CQEVENT EVENT_ON_GROUP_MEMBER_INCREASE(int32_t var0, int32_t var1, int64_t var2, int64_t var3, int64_t var4) { return _on_group_member_increase(var0, var1, var2, var3, var4); }
CQEVENT EVENT_ON_FRIEND_ADD(int32_t var0, int32_t var1, int64_t var2) { return _on_friend_add(var0, var1, var2); }
CQEVENT EVENT_ON_FRIEND_REQUEST(int32_t var0, int32_t var1, int64_t var2, char * var3, char * var4) { return _on_friend_request(var0, var1, var2, var3, var4); }
CQEVENT EVENT_ON_GROUP_REQUEST(int32_t var0, int32_t var1, int64_t var2, int64_t var3, char * var4, char * var5) { return _on_group_request(var0, var1, var2, var3, var4, var5); }
*/
import "C"
