package util

import "testing"

func TestUnpackGroupList(t *testing.T) {
	err := UnpackGroupList("AAAABABEAAAAADOGQH8AAAAAWHjaagAKqVnI9NPqx6fStgAAAAAAAQAAABMAAFwnP4pcoWM7AAAAAAACAAAAAAAAAAAAAAAAAAAARgAAAAAzhkB/AAAAAGXEFuoADKhzhvnTx6erlZnYyAAAAAAAAQAAABQAAFxQNkBcdT/VAAAAAAACAAAAAAAAAAAAAAAAAAAARAAAAAAzhkB/AAAAAGpre0AACs3svv314s/QzaUAAAAAAAEAAAAUAABcStJZXLBr7gAAAAAAAQAAAAAAAAAAAAAAAAAAAEIAAAAAM4ZAfwAAAACQL1MEAAiBN6I4ucjT6gAAAAAAAAAAABQAAFwnP4Vc3ASjAAAAAAADAAAAAAAAAAAAAAAAAAA=")
	if err != nil {
		t.Log("解码出错 ", err)
	}
}
